workout01-report
================
Cameron Ostroot
3/13/2019

Introduction
------------

In 2016 the Golden State Warriors was the number one ranked team within the Western Conference of the NBA. With an overall record of 73 wins and only 9 losses, you can see a huge gap between the Golden State Warriors, and their competitors. So the question is what made the Golden State Warriors such a forced to be reckoned with within the Western Conference of the NBA? There are always several factors to keep into account when analyzing the reason behind a teams win; maybe they are receiving good coaching, maybe they have a "Home Court Advantage" for a given game, maybe they have some star players with inherent talent, or possibly its a combination of all of the previous factors. It is impossible to state definitively a reason why they did so amazing within the 2016 season, but by analyzing some of the statistics of their star players we can potentially see how impressive their athletes are as a result of their intrinsic talent combined with the environmental factors they are put under, such as coaching, and more. From this data we can potentially see who has contributed most towards their excessive winning streak, and therefore draw some conclusions as to the athletes which are responsible to their dominating 73 wins to 9 losses record in 2016.

Motivation
----------

The motivation behind this report is to dive into asking how the Golden State Warriors did so well in the Western Conference's 2016 Season. Specifically, five of their star players will be analyzed: Kevin Durant, Andre Iguodala, Klay Thompson, Stephen Curry, and Draymond Green. From an analysis in following sections, we will be able to conclude who is believed to be the most valuable player by factoring in their shots made, percentage of shots made, and finally factoring in how they contributed to the Golden State Warrior's overall success.

Background
----------

The Golden State Warriors are an American Basketball team based in Oakland, CA, and they are known for their extremely impressive record within the NBA's Western Conference. Within this report, we will specifically look at the Golden State Warrior's data for their 2016 season. Moreover, this report will follow the record and effectiveness of five star players within the Golden State Warriors: Kevin Durant, Andre Iguodala, Klay Thompson, Stephen Curry, and Draymond Green. Stephen Curry, one of the star players was selected as an early pick for the Golden State Warriors from the 2009 NBA Draft, and since then has been a forced to be reckoned with and has soared into being one of the most valuable players on the team. Kevin Durant started his career with the Seattle SuperSonics in 2007, and moved into becoming a star player for the Golden State Warriors in 2016. Andre Iguodala furthermore started his career in 2004, and has moved around since then, specifically moving and having a major influence as a player for the Golden State Warriors in 2015. Klay Thompson, on the other hand is more of a rookie compared to the others, being drafted by the warriors in 2011, and becoming a valuable part of the team from there. Last but not least within this group, Draymond Green is the biggest rookie within the group by being picked by the Golden State Warriors within the 2012 NBA Draft.

Data
----

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

##### Table 1: Effectiveness of 2 Point Shots by Player

    ## # A tibble: 5 x 4
    ##   name           total  made perc_made
    ##   <fct>          <int> <int>     <dbl>
    ## 1 Andre Iguodala   210   134     0.638
    ## 2 Kevin Durant     643   390     0.607
    ## 3 Stephen Curry    563   304     0.540
    ## 4 Klay Thompson    640   329     0.514
    ## 5 Draymond Green   346   171     0.494

##### Table 2: Effectiveness of 3 Point Shots by Player

    ## # A tibble: 5 x 4
    ##   name           total  made perc_made
    ##   <fct>          <int> <int>     <dbl>
    ## 1 Klay Thompson    580   246     0.424
    ## 2 Stephen Curry    687   280     0.408
    ## 3 Kevin Durant     272   105     0.386
    ## 4 Andre Iguodala   161    58     0.360
    ## 5 Draymond Green   232    74     0.319

##### Table 3: Effectiveness of Total Shots by Player

    ## # A tibble: 5 x 4
    ##   name           total  made perc_made
    ##   <fct>          <int> <int>     <dbl>
    ## 1 Kevin Durant     915   495     0.541
    ## 2 Andre Iguodala   371   192     0.518
    ## 3 Klay Thompson   1220   575     0.471
    ## 4 Stephen Curry   1250   584     0.467
    ## 5 Draymond Green   578   245     0.424

##### Figure 1: Display of Where Shots were Made by Player

<img src="../images/gsw-shot-charts.png" width="80%" style="display: block; margin: auto;" />

Analysis
--------

Starting with Table 1 which describes the effectiveness of each player based on their 2 point throws, we can see that overall Iguodala has the best percentage of shots made, which may allow us to believe that he is the most valuable player, but it is important to note that he only made 134 shots overall, as opposed to Kevin Durant making the most 2 point shots with 390 made. From this data, we can potentially be lead to believe that within the 2016 season, Iguodala might have been the most valuable player if he had the opportunity to try to make more 2 point shots overall. However, with a percentage of around 64% made, that is not too off from Durants 61%, yet Durant made a significantly amount more as discussed previously. Similarly Table 2 demonstrates the overall effectiveness of each player based off of their 3 point shot data in 2016. From this, Klay Thompson overall has the best percentage of shots made with 42% made, but Curry demonstrates the most shots made with 280 3 point throws made. Finally, Table 3 describes the overall effectiveness of each player based off of their total percentage and shots made. From this table it is noticeable that Kevin Durant has the best well rounded percentage of general shots made by making 54% of his shots, while Klay Thompson on the other hand is making the most shots overall for the team with 584 shots made.

Discussion
----------

Using the data from the previous tables, along within the analysis above, we can start to discuss what can add up to becoming the most valuable player for the Golden State Warriors in 2016. Overall, it is important to note that the term most valuable is determined purely on contribution to overall points for the team, as opposed to asissting others achieve a point, or any other definition. Based off of this more closed definition of most valuable player, we can make two distinctions within a players value: how valuable they could have been as opposed to how valuable they were. From these distinctions, by analyzing that Iguodala made the had the best 2 point percentage, we are lead to believe that he *could* have been the most valuable player if he had more time in the game, or even took more shots overall (maybe he had the opportunities to take more shots, but only actually took the ones he believed he could make leading to his high percentage made). On the other hand Durant also had an amazing percentage of 2 pointers made, but even more importantly, scored the most 2 pointers overall. From this definition, purely based off of two point throws, Kevin Durant would be the most valuable player for the season. Following this same train of thought, Klay Thompson *could* have been the most valuable player in terms of 3 point shots due to his percentage of shots made being the highest, however Stephen Curry made the most shots overall for three pointers, along with having a pretty good percentage of shots made as well (41% as opposed to Thompson's 42%). Furthermore, though these two previous conclusions are interesting statistics of the 2016 Golden State Warrior Season, perhaps the most important statistics arrise from Table 3 which discuss the overall effectiveness of each of these star players, where Kevin Durant *could* have been the best player due to his great percentage of total shots made averaging out to 54%, but in actuality Stephen Curry made a significant amount of shots more with 584 total shots made.

Conclusions and Take Home Message
---------------------------------

Using the data discussed previously in the Discussion section, and for the purpose of this report, it is important to distinct what *could* have been the most valuable player as opposed to who *actually* was due to the results of total shots made. In actuallity, there is a lot of nuance when it comes to the percentage of shots made, and in all cases the player with the highest percentage of shots made, did not take the most overall shots, which leads to the belief that they have a superior percentage as they are selectively choosing their shots. or aren't given enough playing time. If you look at Figure 1 you can see that even though players may be missing shots all over the board, what matters is how many overall points they tangeably contribute to the team. Overall due to this analysis, I would conclue that Stephen Curry was one of the most, if not **the** most valuable player for the Golden State Warriors within the 2016 season.

References
----------

The following is a list of references displayed by URL which was usefull in receiving information for this report:

<https://www.basketball-reference.com/teams/GSW/2016_games.html>

<https://www.nba.com/players/stephen/curry/201939>

<https://www.nba.com/players/kevin/durant/201142>

<https://www.nba.com/players/andre/iguodala/2738>

<https://www.nba.com/players/klay/thompson/202691>

<https://www.nba.com/players/draymond/green/203110>
